services:
  - type: web
    name: my-web-service
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
